[tool.poetry]
name = "scrapy-selenium4"
version = "0.0.8"
description = "Scrapy middleware for Selenium 4"
authors = ["Jiri <346563+007C39@users.noreply.github.com>"]
readme = "README.md"
package-mode = true

[tool.poetry.dependencies]
python = "^3.12"
selenium = "^4.29.0"
Scrapy = "^2.12.0"

[tool.poetry.group.test.dependencies]
pytest = "^8.3.5"

[tool.poetry.group.dev.dependencies]
mccabe = "^0.7.0"
flake8 = "^7.1.2"
pycodestyle = "^2.12.1"
pylint = "^3.3.5"
bandit = "^1.8.3"
ruff = "^0.11.0"
dodgy = "^0.2.1"
vulture = "^2.14"
pdoc3 = "^0.11.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
